### ISSUE TITLE
Switch on the Discussions

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-IIoT-StarterKit#8]
Discussions are the space for your community to have conversations, ask questions, and post answers without opening issues.

**Comment by opcfoundation-org** [comment]
done

**Comment by mpostol** [comment]
Thanks,

**Comment by Mentor-Roma** [comment]
Hello 
I have some worries concerning this project.

I have been trying to get a running demo for OPC UA pub-sub, but no success.

1. When setting up the linux computer as prescribed [here](https://github.com/OPCFoundation/UA-IIoT-StarterKit/tree/master/docs/setup/linux), the repository provided for cloning the project (git clone https://github.com/OPCF-Members/UA-IIoT-StarterKit.git) seems not to exist. Is it for members of the OPC UA foundation only?
2. Given that the provided repository doesn't work, I cloned this one into my local repo, but can't build the mqttagent successfully. I tried also with same config as given (vscode 19, dotnet 50...) Yet, no success. 
Can someone help with a hint?

Here is the error build message from cmd

/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:  ---> System.DllNotFoundException: Unable to load shared library '/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/MSBuildCore/../runtimes/ubuntu.18.04-x64/native/libgit2-106a5f2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libssl.so.1.1: cannot open shared object file: No such file or directory [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.GitLoaderContext.LoadUnmanagedDll(String unmanagedDllName) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods..cctor() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    --- End of inner exception stack trace --- [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.Proxy.git_libgit2_opts_set_search_path(ConfigurationLevel level, String path) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.Create(String projectDirectory, String gitRepoDirectory, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]

Build FAILED.

/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:  ---> System.DllNotFoundException: Unable to load shared library '/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/MSBuildCore/../runtimes/ubuntu.18.04-x64/native/libgit2-106a5f2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libssl.so.1.1: cannot open shared object file: No such file or directory [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.GitLoaderContext.LoadUnmanagedDll(String unmanagedDllName) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods..cctor() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    --- End of inner exception stack trace --- [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.Core.Proxy.git_libgit2_opts_set_search_path(ConfigurationLevel level, String path) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.Create(String projectDirectory, String gitRepoDirectory, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot) [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
/home/roma/.nuget/packages/nerdbank.gitversioning/3.2.31/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner() [/home/roma/UA-IIoT-StarterKit/OpcUa/Libraries/Opc.Ua.Security.Certificates/Opc.Ua.Security.Certificates.csproj]
    0 Warning(s)
    1 Error(s)
